/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fs.api.frames.filtros;

import br.com.fs.api.dal.EntityManagerHelper;
import br.com.fs.api.interfaces.ListenerPatternAdapter;
import br.com.fs.api.interfaces.TableModelDefaultAdapter;
import br.com.fs.api.interfaces.ManipulaFrames;
import br.com.fs.api.util.REGEX;
import br.com.fs.api.util.RegexUtil;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.event.CaretEvent;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author tiago.teixeira
 */
public final class SeletorLista extends ManipulaFrames {

    private static final long serialVersionUID = -2154580416248090228L;
    private TableModelDefaultAdapter model;
    private EntityManagerHelper emh;
    private List<?> lista;

    /**
     * Creates new form SeletorPrestador
     *
     * @param emh
     */
    public SeletorLista(EntityManagerHelper emh) {
        setImageIcon();
        this.emh = emh;
        initComponents();
    }

    public void setParameters(List<?> lista, TableModelDefaultAdapter model, int... columnSize){
        this.lista = lista;
        this.model = model;
        this.mountModel(columnSize);
    }
    
    private void mountModel(int... columSize) {
        model.addLista(lista == null ? new ArrayList() : lista);
        TableRowSorter sorter = new TableRowSorter(model);
        tbPrestador.setModel(model);
        tbPrestador.setRowSorter(sorter);
        ListenerPatternAdapter lca = new ListenerPatternAdapter(this);
        //lca.setColumnSize(tbPrestador, columSize);

        txtPesquisa.addCaretListener((CaretEvent e) -> {
            sorter.setRowFilter(RowFilter.regexFilter(RegexUtil.getRegex(REGEX.CONTEM, txtPesquisa.getText())));
        });

    }

    public JTable getTbPrestador() {
        return tbPrestador;
    }

    public void setTbPrestador(JTable tbPrestador) {
        this.tbPrestador = tbPrestador;
    }

    public TableModelDefaultAdapter getModel() {
        return model;
    }

    public void setModel(TableModelDefaultAdapter model) {
        this.model = model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scPrestador = new javax.swing.JScrollPane();
        tbPrestador = new javax.swing.JTable();
        lbPesquisa = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisa de Prestadores");

        tbPrestador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scPrestador.setViewportView(tbPrestador);

        lbPesquisa.setText("Filtro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scPrestador, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisa)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPesquisa)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scPrestador, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeletorLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeletorLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeletorLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeletorLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbPesquisa;
    private javax.swing.JScrollPane scPrestador;
    private javax.swing.JTable tbPrestador;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables

}
