/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fs.api.frames;

import br.com.fs.api.dal.EntityManagerHelper;
import br.com.fs.api.interfaces.ListenerPatternAdapter;
import br.com.fs.api.util.ControleInstancias;
import br.com.fs.api.interfaces.ManipulaFrames;
import br.com.fs.api.interfaces.entities.Usuario;
import br.com.fs.api.util.ControleUsuario;
import br.com.fs.api.util.Utilidades;
import com.sun.glass.events.KeyEvent;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.Serializable;
import java.util.Objects;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Tiago D. Teixeira
 */
public final class Form_Login extends ManipulaFrames {

    private static final long serialVersionUID = 1940296401210395397L;

    /**
     * Creates new form loginForm
     */
    private final Listener_Login listener;

    public Form_Login(EntityManagerHelper emh) {
        setImageIcon();
        initComponents();
        listener = new Listener_Login(this, emh);
    }

    public void closeSplash() {
        Form_Splash splashForm = (Form_Splash) ControleInstancias.getInstance(Form_Splash.class.getName());
        if (splashForm != null) {
            splashForm.dispose();
        }
    }

    public JButton getBtLogin() {
        return btLogin;
    }

    public JButton getBtSenha() {
        return btSenha;
    }

    public JPasswordField getTxtSenha() {
        return txtSenha;
    }

    public JTextField getTxtUsuario() {
        return txtUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ButtonPanel = new javax.swing.JPanel();
        btLogin = new javax.swing.JButton();
        btSenha = new javax.swing.JButton();
        menuBarCbiDefault = new br.com.fs.api.beans.MenuBarCbiDefault();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SRES - Sistema de Registro Eletrônico em Saúde");
        setResizable(false);

        MainPanel.setPreferredSize(new java.awt.Dimension(400, 200));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema de Registro Eletrônico em Saúde");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Usuário");

        txtUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setToolTipText("");
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Senha");

        txtSenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSenha.setToolTipText("");
        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Reconhecimento da Assinatura Digital");

        jLabel5.setBackground(new java.awt.Color(255, 204, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Insira o Cartão do Certificado");
        jLabel5.setOpaque(true);

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsuario)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSenha)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        btLogin.setText("Login");
        btLogin.setActionCommand("login");
        btLogin.setPreferredSize(new java.awt.Dimension(100, 23));

        btSenha.setText("Cancelar");
        btSenha.setToolTipText("");
        btSenha.setActionCommand("cancelar");
        btSenha.setPreferredSize(new java.awt.Dimension(100, 23));

        javax.swing.GroupLayout ButtonPanelLayout = new javax.swing.GroupLayout(ButtonPanel);
        ButtonPanel.setLayout(ButtonPanelLayout);
        ButtonPanelLayout.setHorizontalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(btSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        ButtonPanelLayout.setVerticalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuBarCbiDefault.setMinimumSize(new java.awt.Dimension(0, 0));
        menuBarCbiDefault.setPreferredSize(new java.awt.Dimension(0, 0));
        setJMenuBar(menuBarCbiDefault);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER:
                if (getTxtSenha().getPassword().length > 0) {
                    getBtLogin().doClick();
                } else {
                    getTxtSenha().requestFocus();
                }
        }
    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void txtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER:
                if (!Objects.equals(getTxtUsuario().getText(), null) && !Objects.equals(getTxtUsuario().getText(), "")) {
                    getBtLogin().doClick();
                } else {
                    getTxtUsuario().requestFocus();
                }
        }
    }//GEN-LAST:event_txtSenhaKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton btLogin;
    private javax.swing.JButton btSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private br.com.fs.api.beans.MenuBarCbiDefault menuBarCbiDefault;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    public final class Listener_Login extends ListenerPatternAdapter<Form_Login> implements ActionListener, Serializable {

        private static final long serialVersionUID = -6735813835735026392L;
        private final EntityManagerHelper emh;

        public Listener_Login(Form_Login form, EntityManagerHelper emh) {
            super(form);
            initComponents();
            this.emh = emh;
        }

        @Override
        protected void initComponents() {
            attachListener();
        }

        @Override
        protected void attachListener() {
            form.getBtLogin().addActionListener(this);
            form.getBtSenha().addActionListener(this);
            form.getItemFechar().addActionListener(this);
        }

        private void openMainForm(boolean abrir) {
            if (abrir) {
                Form_Main formMain = (Form_Main) ControleInstancias.getInstance(Form_Main.class.getName());
                formMain.setVisible(true);
            }
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            form.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            switch (e.getActionCommand()) {
                case "login":
                    if (sessionLogin(form.getTxtUsuario().getText(), String.valueOf(form.getTxtSenha().getPassword()))) {
                        openMainForm(true);
                        form.dispose();
                    } else {
                        JOptionPane.showMessageDialog(form, "Não foi possível iniciar a sessão, contate o administrador do sistema", "Erro de autenticação", JOptionPane.ERROR_MESSAGE);
                    }
                    break;
                case "cancelar":
                    form.fecharSistema();
                    break;
                case "fechar":
                    form.fecharSistema();
                    break;
            }
            form.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }

        private boolean sessionLogin(String login, String senha) {
            try {
                //byte[] dados = Utilidades.encryptMsg((login + "," + senha + ",S34M3D"));
                Optional<Usuario> usuario = emh.getObjectNamedQuery(Usuario.class, "usuario.findByUser", "paramUser", login, EntityManagerHelper.DERBYDB_PU);
                if (usuario.isPresent()) {
                    if (usuario.get().getSenha().equals(Utilidades.encriptyPassword(senha))) {
                        ControleUsuario.setUsuarioAtual(usuario.get());
                        return true;
                    }
                }
                return false;
                //return login.equals("admin") && senha.equals("admin");
            } catch (Exception ex) {
                Logger.getLogger(Listener_Login.class.getName()).log(Level.SEVERE, null, ex);
                return false;
            }
        }
    }

}
