/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fs.api.frames;

import br.com.fs.api.dal.EntityManagerHelper;
import br.com.fs.api.util.ControleInstancias;
import br.com.fs.api.interfaces.ManipulaFrames;
import br.com.fs.api.util.ConfigUtil;
import br.com.fs.api.util.Utilidades;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.KeyStroke;
import javax.swing.Timer;

/**
 *
 * @author Tiago D. Teixeira
 */
public final class Form_Splash extends ManipulaFrames {

    private static final long serialVersionUID = -1008960028915377183L;

    private Timer t;

    /**
     * Creates new form SplashForm
     */
    public Form_Splash(EntityManagerHelper emh, ManipulaFrames main_frame, String title) {
        Utilidades.mudaLookAndFeel(Utilidades.WINDOWS);
        setImageIcon();
        initComponents();
        this.fecharESC(menuBarCbiDefault.getItemFechar());
        jLabel1.setIcon(new ImageIcon(ConfigUtil.getImageSplashFile()));
        carregarSistema(emh, main_frame, title);
    }

    private void fecharESC(JMenuItem menuItem) {
        KeyStroke escape = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
        menuItem.setAccelerator(escape);
    }

    public void carregarSistema(EntityManagerHelper emh, ManipulaFrames main_frame, String title) {

        ControleInstancias.setControleInstancias(Form_Splash.class.getName(), this);

        new Thread() {
            @Override
            public void run() {
                Form_Login loginForm = (Form_Login) ControleInstancias.getInstance(Form_Login.class.getName());
                loginForm.setEntityManagerHelper(emh, main_frame, title);
                loginForm.closeSplash();
                loginForm.setVisible(true);
            }
        }.start();

        ActionListener listener = (ActionEvent e) -> {
            if (progressBar.getValue() < 100) {
                progressBar.setValue(progressBar.getValue() + 2);
            }
        };

        t = new Timer(100, listener);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        menuBarCbiDefault = new br.com.fs.api.beans.MenuBarCbiDefault();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setPreferredSize(new java.awt.Dimension(424, 182));

        jLabel3.setText("Sistema - versão 1.0");

        menuBarCbiDefault.setMinimumSize(new java.awt.Dimension(0, 0));
        menuBarCbiDefault.setPreferredSize(new java.awt.Dimension(0, 0));
        setJMenuBar(menuBarCbiDefault);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        t.stop();
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private br.com.fs.api.beans.MenuBarCbiDefault menuBarCbiDefault;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
