/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fs.api.frames;

import br.com.fs.api.interfaces.ListenerPatternAdapter;
import br.com.fs.api.interfaces.ManipulaFrames;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 * @author tiago.teixeira
 */
public final class Form_ReportManager extends ManipulaFrames {

    private static final long serialVersionUID = -7073981777488467088L;
    private ListenerPatternAdapter listener;
    /**
     * Creates new form Form_ReportManager
     */
    public Form_ReportManager() {
    }

    public Form_ReportManager(ListenerPatternAdapter listener) {
        setImageIcon();
        initComponents();
        this.listener = listener;
        painelBarraProgresso.setVisible(false);
    }
    
    public JPanel getPainelBarraProgresso() {
        return painelBarraProgresso;
    }

    public JButton getBtEditarFiltro() {
        return btEditarFiltro;
    }

    public JButton getBtImprimir() {
        return btImprimir;
    }

    public JPanel getPainelMain() {
        return painelMain;
    }

    public JScrollPane getScFiltros() {
        return scFiltros;
    }

    public JScrollPane getScGrupos() {
        return scGrupos;
    }

    public JScrollPane getScReports() {
        return scReports;
    }

    public JTable getTbFiltros() {
        return tbFiltros;
    }

    public JTable getTbGrupos() {
        return tbGrupos;
    }

    public JTable getTbReports() {
        return tbReports;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelMain = new javax.swing.JPanel();
        scGrupos = new javax.swing.JScrollPane();
        tbGrupos = new javax.swing.JTable();
        scReports = new javax.swing.JScrollPane();
        tbReports = new javax.swing.JTable();
        scFiltros = new javax.swing.JScrollPane();
        tbFiltros = new javax.swing.JTable();
        painelBarraProgresso = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbProgresso = new javax.swing.JLabel();
        bpProgresso = new javax.swing.JProgressBar();
        btEditarFiltro = new javax.swing.JButton();
        btImprimir = new javax.swing.JButton();
        menuBarCbiDefault = new br.com.fs.api.beans.MenuBarCbiDefault();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciador de Relatórios");

        tbGrupos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Grupos de Relatórios"
            }
        ));
        scGrupos.setViewportView(tbGrupos);

        tbReports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Relatórios"
            }
        ));
        scReports.setViewportView(tbReports);

        tbFiltros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Filtro", "Valor"
            }
        ));
        scFiltros.setViewportView(tbFiltros);

        jLabel1.setText("Gerando Relatório:");

        lbProgresso.setText("0");

        javax.swing.GroupLayout painelBarraProgressoLayout = new javax.swing.GroupLayout(painelBarraProgresso);
        painelBarraProgresso.setLayout(painelBarraProgressoLayout);
        painelBarraProgressoLayout.setHorizontalGroup(
            painelBarraProgressoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBarraProgressoLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(painelBarraProgressoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bpProgresso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelBarraProgressoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbProgresso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(2, 2, 2))
        );
        painelBarraProgressoLayout.setVerticalGroup(
            painelBarraProgressoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBarraProgressoLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(painelBarraProgressoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbProgresso))
                .addGap(2, 2, 2)
                .addComponent(bpProgresso, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        btEditarFiltro.setText("Editar Filtro");
        btEditarFiltro.setActionCommand("editar");
        btEditarFiltro.setPreferredSize(new java.awt.Dimension(93, 23));

        btImprimir.setText("Imprimir");
        btImprimir.setActionCommand("imprimir");
        btImprimir.setPreferredSize(new java.awt.Dimension(93, 23));

        javax.swing.GroupLayout painelMainLayout = new javax.swing.GroupLayout(painelMain);
        painelMain.setLayout(painelMainLayout);
        painelMainLayout.setHorizontalGroup(
            painelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scReports)
                    .addComponent(scFiltros, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelMainLayout.createSequentialGroup()
                        .addComponent(painelBarraProgresso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5)
                        .addComponent(btEditarFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        painelMainLayout.setVerticalGroup(
            painelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scGrupos, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                    .addGroup(painelMainLayout.createSequentialGroup()
                        .addComponent(scReports, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(painelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btEditarFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(painelBarraProgresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)))
                .addContainerGap())
        );

        menuBarCbiDefault.setMinimumSize(new java.awt.Dimension(0, 0));
        menuBarCbiDefault.setPreferredSize(new java.awt.Dimension(0, 0));
        setJMenuBar(menuBarCbiDefault);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar bpProgresso;
    private javax.swing.JButton btEditarFiltro;
    private javax.swing.JButton btImprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbProgresso;
    private br.com.fs.api.beans.MenuBarCbiDefault menuBarCbiDefault;
    private javax.swing.JPanel painelBarraProgresso;
    private javax.swing.JPanel painelMain;
    private javax.swing.JScrollPane scFiltros;
    private javax.swing.JScrollPane scGrupos;
    private javax.swing.JScrollPane scReports;
    private javax.swing.JTable tbFiltros;
    private javax.swing.JTable tbGrupos;
    private javax.swing.JTable tbReports;
    // End of variables declaration//GEN-END:variables

}
