/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fs.api.frames;

import br.com.fs.api.dal.EntityManagerHelper;
import br.com.fs.api.interfaces.ManipulaFrames;
import br.com.fs.api.interfaces.entities.Frame_Sistema;
import br.com.fs.api.util.ControleInstancias;
import java.awt.Component;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;
import javax.swing.AbstractButton;
import javax.swing.JComboBox;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JTable;

/**
 *
 * @author tiago.teixeira
 */
public final class Form_Main extends ManipulaFrames {

    private static final long serialVersionUID = -419029088399611882L;

    /**
     * Creates new form Main_Form
     */
    public Form_Main() {
        setImageIcon();
        initComponents();
        stateForm();
        startStatusBar();
        report_manager();
        //cadastrarTelas();
    }

    private void report_manager() {
        itemGerenciadorRelatorios.addActionListener(event -> {
            switch (event.getActionCommand()) {
                case "reportManager":
                    Form_ReportManager report = new Form_ReportManager();
                    ControleInstancias.setControleInstancias(report.getName(), report);
                    report.setVisible(true);
                    break;
            }
        });
    }

    private void stateForm() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    @Override
    public JMenuItem getItemFechar() {
        return itemFechar;
    }

    private void startStatusBar() {
        statusBar.startStatusBar(this);
    }

    @Override
    public Optional<List<AbstractButton>> getListMenus() {
        List<AbstractButton> lista = new ArrayList();
        forMenu(menuBarCbiDefault.getComponents(), lista);
        return Optional.ofNullable(lista);
    }

    public List<AbstractButton> getMenuList() {
        List<AbstractButton> lista = new ArrayList();
        forMenu(menuBarCbiDefault.getComponents(), lista);
        return lista;
    }

    public boolean internalFrameIsOpen(JInternalFrame iframe) {
        return false;//listener.internalFrameIsOpen(iframe);
    }

    private void forMenu(Component[] components, List<AbstractButton> lista) {
        for (Component comp : components) {
            if (comp instanceof JMenu) {
                JMenu menu = (JMenu) comp;
                for (Component a : menu.getMenuComponents()) {
                    if (a instanceof JMenu) {
                        JMenu m = (JMenu) a;
                        forMenu(m.getMenuComponents(), lista);
                    } else if (a instanceof JMenuItem) {
                        JMenuItem i = (JMenuItem) a;
                        lista.add(i);
                    }
                }
            } else if (comp instanceof JMenuItem) {
                JMenuItem i = (JMenuItem) comp;
                lista.add(i);
            }
        }
    }

    public JMenuItem getItemGerenciadorRelatorios() {
        return itemGerenciadorRelatorios;
    }

    private void cadastrarTelas(EntityManagerHelper emh) {
        getListMenus().ifPresent(lista -> {
            lista.stream()
                    .filter(menu -> !menu.getText().equals("Logout") && !menu.getText().equals("Fechar"))
                    .forEach(menu -> emh.getOperation(EntityManagerHelper.ATUALIZAR, new Frame_Sistema(null, null, menu.getText()), EntityManagerHelper.DERBYDB_PU));
        });
    }

    public JDesktopPane getDesktopPane() {
        return desktopPane;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        desktopPane = new javax.swing.JDesktopPane();
        statusBar = new br.com.fs.api.beans.JStatusBarCBI();
        menuBarCbiDefault = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuCadastroGeral = new javax.swing.JMenu();
        separador1 = new javax.swing.JPopupMenu.Separator();
        itemLogout = new javax.swing.JMenuItem();
        itemFechar = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        itemGerenciadorRelatorios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema");
        setName("main_form"); // NOI18N

        desktopPane.setMinimumSize(new java.awt.Dimension(685, 505));
        desktopPane.setOpaque(false);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menuArquivo.setText("Arquivo");

        menuCadastroGeral.setText("Cadastros");
        menuArquivo.add(menuCadastroGeral);
        menuArquivo.add(separador1);

        itemLogout.setText("Logout");
        itemLogout.setActionCommand("logout");
        menuArquivo.add(itemLogout);

        itemFechar.setText("Fechar");
        itemFechar.setActionCommand("fechar");
        menuArquivo.add(itemFechar);

        menuBarCbiDefault.add(menuArquivo);

        menuRelatorios.setText("Relatórios");

        itemGerenciadorRelatorios.setText("Gerenciador de Relatórios");
        itemGerenciadorRelatorios.setActionCommand("reportManager");
        menuRelatorios.add(itemGerenciadorRelatorios);

        menuBarCbiDefault.add(menuRelatorios);

        setJMenuBar(menuBarCbiDefault);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(statusBar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 904, Short.MAX_VALUE)
                    .addComponent(panelMain, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(statusBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem itemFechar;
    private javax.swing.JMenuItem itemGerenciadorRelatorios;
    private javax.swing.JMenuItem itemLogout;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuBar menuBarCbiDefault;
    private javax.swing.JMenu menuCadastroGeral;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPopupMenu.Separator separador1;
    private br.com.fs.api.beans.JStatusBarCBI statusBar;
    // End of variables declaration//GEN-END:variables

}
